### ISSUE TITLE
How to Get the Post data?

### ISSUE THREAD

**Issue by xjdata** [jchristn/WatsonWebserver#10]
How to Get the post data?
thank you.

**Comment by jchristn** [comment]
Hi, it’s in HttpRequest.Data (byte[])

**Comment by xjdata** [comment]
tks   i  used https://github.com/Vodurden/Http-Multipart-Data-Parser  parser data.

**Comment by jchristn** [comment]
Ah, sorry, I thought you were asking about where the data was stored. What kind of request body are you working with?
