### ISSUE TITLE
How to set the filter mime type

### ISSUE THREAD

**Issue by sqlnew** [jchristn/WatsonWebserver#105]
Hi,
When I set the local static folder, specify Routes.Content.Add, and how to set the filter to prevent the specific mime type files from being accessed or downloaded; How to add a mime type file to make it a downloadable and accessible file type?

**Comment by jchristn** [comment]
Hi @sqlnew there isn't a way to further filter invocation of a route based on a MIME type.  I like the idea of adding more annotations that filter when a route is used.  But for now, it would have to be handled in your route body.

**Comment by sqlnew** [comment]
Thank you!
