### ISSUE TITLE
Spaces when using Content Routes

### ISSUE THREAD

**Issue by Linqx** [jchristn/WatsonWebserver#11]
Original Code:
![image](https://user-images.githubusercontent.com/14795987/37937685-9af48426-310f-11e8-8b7e-d8396f39ac61.png)

Viable Fix:
![image](https://user-images.githubusercontent.com/14795987/37937721-c611e978-310f-11e8-9812-02f109d49710.png)

Code doesn't convert "%20" and "+" to " " when checking if the file exists.

**Comment by jchristn** [comment]
Thanks @Linqx , I'll get that implemented right now!

**Comment by Linqx** [comment]
No problem @jchristn, glad I could help!

**Comment by jchristn** [comment]
Just committed, v1.2.11 is in queue for indexing on NuGet right now.  Thanks again!  https://github.com/jchristn/WatsonWebserver/commit/968817467d5650d732a96baa21d27ee0e1f74eb5
