### ISSUE TITLE
IPAddress.Any not support

### ISSUE THREAD

**Issue by almoshammer** [jchristn/WatsonWebserver#118]
Whan use ip 0.0.0.0 that refer to any interface, shows ip not supported

**Comment by jchristn** [comment]
Which operating system are you using?

Which framework/runtime and version are you using?

Are you running as administrator?

**Comment by almoshammer** [comment]
> Which version of Watson are you using?
> The last version,
> Which operating system are you using?
> .Windows 11,
> Which framework/runtime and version are you using?
> .Net 4.8
> Are you running as administrator?
> I tried both

**Comment by jchristn** [comment]
When you say it's not supported, are you referring to not being able to pass in ```IPAddress.Any``` to the constructor (or via settings)?

With the ```Test.Default``` project, running as administrator on Windows 11, the server works fine on .NET 4.8 and also 6.0, 7.0, etc (just change ```_Hostname``` to ```*```)

![image](https://github.com/jchristn/WatsonWebserver/assets/1421081/0fa3411f-5307-44c7-b8ca-4fd2b03233be)

**Comment by jchristn** [comment]
BTW, I just confirmed that multiple people have had issues using ```0.0.0.0```.  Use ```*``` or ```+``` instead.  I'll check my README etc to make sure they don't reference ```0.0.0.0```.

**Comment by almoshammer** [comment]
Ok, Thanks for great work.

**Comment by jchristn** [comment]
Thanks @almoshammer I hope you have a great week and please let me know if you run into any issues!
