### ISSUE TITLE
IP works, but not hostname

### ISSUE THREAD

**Issue by winkmichael** [jchristn/WatsonWebserver#15]
Using IP address works

Works:
Server s = new Server("192.168.1.50, 80, false, DefaultRoute, debug_mode);
I get the output from the Default method fine

However, I have a DNS entry to API.mydomain.com pointing at 192.168.1.50 and when I try to do the same get command I get

Bad Request (Invalid host)

Nothing shows up in the debug logs either.

Ideas, or suggestions?

**Comment by jchristn** [comment]
Hi @winkmichael thanks for your note.  I just tested by adding an entry into \windows\system32\drivers\etc\hosts for www.localhost.com pointing to 127.0.0.1 and tested this out and it worked.  Are you using .NET Core or .NET Framework (and which version)?  Also are you running Watson as a standard user or under a user with administrative privileges?

**Comment by winkmichael** [comment]
Thanks for your prompt reply! Really enjoying working with your project. I hadn't edited the code for many months and forgot I have NGINX proxying in front it, sorry for the confusion. It works great. Thanks again

**Comment by winkmichael** [comment]
I am sorry for reopening this, but upon even further review I do the following;

Server s = new Server(192.168.1.5, 9000, false, DefaultRoute, debug_mode);

I can browse to http://192.168.1.5:9000 just fine

I happen to have a DNS address pointing watson.mydomain.com at 192.168.1.5, when I browse to http://watson.mydomain.com:9000/ I am instantly returned with "Not Found (Not Found)"

If I modify the server to be;

Server s = new Server(watson.mydomain.com, 9000, false, DefaultRoute, debug_mode);

I can then browse to http://watson.mydomain.com:9000/, but now browsing to http://192.168.1.5:9000 returns Not Found (Not Found)


Looking at the AcceptConnections, it seems an array could be easily included 

  private void AcceptConnections(CancellationToken token)
        {
            try
            {
                if (ListenerSsl) ListenerPrefix = "https://" + ListenerIp + ":" + ListenerPort + "/";
                else ListenerPrefix = "http://" + ListenerIp + ":" + ListenerPort + "/";
                Http.Prefixes.Add(ListenerPrefix);
                Http.Start();

In my case I would love to be able to have multiple hostnames point at the system.

Thank you very much for your time and help!

**Comment by winkmichael** [comment]
FYI, I work around this using an upstream filter to regex

**Comment by jchristn** [comment]
Hi @winkmichael thanks for re-opening.  I added another constructor that will allow you to pass in a ```List<string>``` and tested under both .NET Framework and .NET Core.  Please refer to commit https://github.com/jchristn/WatsonWebserver/commit/4dd96f757e4b6ca103ff690c7002627f5b4c123d and see updated NuGet package v1.5.2 here: https://www.nuget.org/packages/Watson/1.5.2 (will take some time to index etc).  Thanks!

**Comment by winkmichael** [comment]
Thanks that looks very cool, I feel like something is missing from the 1.5.2 I seem to see it still looking for a string as the input.

My test code; 

List<string> hostnames = new List<string>();
hostnames.Add("192.168.1.5");
hostnames.Add("reporttool.mydomain.com");
hostnames.Add("reporttool.mydomainbackup.com");
Server s = new Server(hostnames, listen_port, false, DefaultRoute, debug_mode);

---
An exception was encountered which triggered this message
  Method     : AcceptConnections
  Type       : System.Net.HttpListenerException
  Data       : System.Collections.ListDictionaryInternal
  Inner      : 
  Message    : The request is not supported.
  Source     : System.Net.HttpListener
  StackTrace :    at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
   at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
   at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
   at System.Net.HttpListener.Start()
   at WatsonWebserver.Server.AcceptConnections(CancellationToken token)
  Stack      : StackToString <= LogException <= AcceptConnections <= RunInternal <= ExecuteWithThreadLocal <= Dispatch
  Line       : 0
  File       : 
  ToString   : System.Net.HttpListenerException (50): The request is not supported.
   at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
   at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
   at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
   at System.Net.HttpListener.Start()
   at WatsonWebserver.Server.AcceptConnections(CancellationToken token)
  Servername : svr-dal-45

**Comment by jchristn** [comment]
You have to run as a privileged user for HttpListener to support multiple prefixes.

**Comment by winkmichael** [comment]
Thanks, but I am root

**Comment by jchristn** [comment]
Are you testing this on .NET Core or .NET Framework?  Linux I assume?

One of the reasons I did not have this in previous versions was because Linux via Mono had issues with binding multiple prefixes to HttpListener.

**Comment by winkmichael** [comment]
Thank you very much again.
Running .NET Core on Linux and OSX at the moment.

My feeling is the method should have an address to bind / listen on, and then the list<string> of the hostnames to use. 

As root on OSX I get the same error;

sudo dotnet ReportCollector.dll
---
An exception was encountered which triggered this message
  Method     : AcceptConnections
  Type       : System.Net.HttpListenerException
  Data       : System.Collections.ListDictionaryInternal
  Inner      : 
  Message    : Can't assign requested address
  Source     : System.Net.HttpListener
  StackTrace :    at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
   at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
   at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
   at System.Net.HttpListener.Start()
   at WatsonWebserver.Server.AcceptConnections(CancellationToken token)
  Stack      : StackToString <= LogException <= AcceptConnections <= RunInternal <= ExecuteWithThreadLocal <= Dispatch
  Line       : 0
  File       : 
  ToString   : System.Net.HttpListenerException (49): Can't assign requested address
   at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
   at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
   at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
   at System.Net.HttpListener.Start()
   at WatsonWebserver.Server.AcceptConnections(CancellationToken token)
  Servername : Michaels-MacBook-ProX.local
---

**Comment by jchristn** [comment]
I think this is a larger issue with .NET Core on Linux/Mac, please see here for a starting point.  https://github.com/dotnet/corefx/issues/19827
