### ISSUE TITLE
"Data" member is null when using HttpMethod.POST

### ISSUE THREAD

**Issue by user4000** [jchristn/WatsonWebserver#16]
I found the program’s strange behavior and want to let you know about it.
Here is an example:

public void Main()
{
Server s = ...
s.AddStaticRoute(HttpMethod.POST, "/employee/", PostEmployee);
}

then I define a method

internal static HttpResponse PostEmployee(HttpRequest arg)
{
 ... body of the method ...
  // ---  oh no !     arg.Data == null   !
}

The issue is:

when I try to read data from the arg.Data member, it turns out that this variable is null !

I invented a way to get around this annoying feature - that's what I'm doing (HttpListenerContext class helps me).

    internal static object ExtractObject(HttpRequest arg)
    {
        HttpListenerContext context = arg.ListenerContext;
        MemoryStream ms = new MemoryStream();
        context.Request.InputStream.CopyTo(ms);
        byte[] array = ms.ToArray();
        return TTConvert.ByteArrayToObject(array); // Here I used my own static class TTConvert to convert byte array to an object
    }

This method returns non-empty byte-array (at the same time arg.Data is null) and after that I can extract an object of my class from this array.

Could you fix your program such way that the variable arg.Data returns a non-null value?

**Comment by jchristn** [comment]
Hi @user4000 yes indeed, I will look into this right away.  Thanks for letting me know!

**Comment by jchristn** [comment]
Also, are you using .NET Core or .NET Framework (and which version)?

**Comment by jchristn** [comment]
Found the bug, fixing and repackaging now.  Commit and NuGet update coming momentarily, will comment commit here.

**Comment by jchristn** [comment]
Updated NuGet: https://www.nuget.org/packages/Watson/1.5.1  (will be available momentarily)
Commit is here: https://github.com/jchristn/WatsonWebserver/commit/6c3fe96c4cc5d84cefe930395464c195d577490b

Thanks so much for catching this!  Please re-open if this doesn't fix it for you, but it worked in my testing.

**Comment by user4000** [comment]
> Also, are you using .NET Core or .NET Framework (and which version)?
Net Framework 4.6.2

**Comment by user4000** [comment]
yes, it works! thank you!
