### ISSUE TITLE
Dynamic file destinations?

### ISSUE THREAD

**Issue by dbuzz111** [jchristn/WatsonWebserver#18]
Hi JChristn,

I was wondering if there is a way to have dynamic file routes? For example we generate a package using $filename.$epoch.zip (profile.1553088047.zip) This file typically only exists for a short period of time etc.

Any suggestions on how to make a route like this?

Thank you ever so much!

**Comment by jchristn** [comment]
Hi @dbuzz111 if you are only planning to use GET, you can use content routes.  ```.AddContentRoute("/html/", true);``` will expose an entire directory, making it available for GET requests.  Would that work for your use case?  Cheers!

**Comment by jchristn** [comment]
Hi @dbuzz111 please re-open the issue if needed.  Assuming this will meet your need.  Thanks
