### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by Malalicious** [jchristn/WatsonWebserver#2]
I've had WatsonWebserver running for a while without SSL. It's pretty common to run webservices (even simple ones) under SSL nowadays. I've set the boolean in the constructor to true but I have no way to specify a certificate. Is there any how-to on this specific topic?

Thanks.

**Comment by jchristn** [comment]
Hi Malalicious, thanks for filing this.  SSL certificates must be bound in the operating system beneath the server.  For Windows, use netsh http (see https://msdn.microsoft.com/en-us/library/ms733791(v=vs.110).aspx), and for Mono, use certmgr and mozroots (see http://www.mono-project.com/docs/faq/security/).

Which OS are you using?

Cheers,
Joel

**Comment by jchristn** [comment]
Hi Malalicious, please let me know if this is helpful.  Closing the issue but if you feel I need to add more, let me know and I'll reopen it!  Thanks!   https://github.com/jchristn/WatsonWebserver/wiki/Using-SSL-on-Windows
