### ISSUE TITLE
newtonsoft.json dependency

### ISSUE THREAD

**Issue by absid89** [jchristn/WatsonWebserver#21]
Hi. Sorry for the dumb question, but is it possible in dependencies to lower the version of the Newtonsoft.Json package by 11? I use this server in WinForms with TelegramBot and when updating your package, the project stops working due to different versions of Newtonsoft.Json packages. Thanks.

**Comment by jchristn** [comment]
Hi @absid that should work with no issue. Give it a go and let me know!

**Comment by absid89** [comment]
Its work but only with 1.4.0 
![watson](https://user-images.githubusercontent.com/26306868/59819605-40b82000-9331-11e9-8583-499357fcb2a8.png)

**Comment by jchristn** [comment]
Oh, I see what you're asking.  Sorry for misunderstanding.  I just modified the dependencies to support down to 11.0 (couldn't go any lower without affecting other libraries) and submitted NuGet package v2.0.5, so it should be available shortly!  https://www.nuget.org/packages/Watson/2.0.5

**Comment by absid89** [comment]
Thanks a lot! Now I can use latest version with all features. And Sorry for my bad English if this caused misunderstanding.

**Comment by jchristn** [comment]
You are very welcome @absid89 - I'm glad I could help.  And please don't apologize for your English, it was quite good, and you are much more proficient in English than I would be in someone else's native language!  Have a very good day
