### ISSUE TITLE
Project NET Framework 4.6.2 upgrade Watson Webserver to 2.1.2 failed

### ISSUE THREAD

**Issue by timur4000** [jchristn/WatsonWebserver#22]
Hello, Joel !

My problem is: I could not upgrade Watson Webserver in my project from 2.0.2 to 2.1.2 because Package Manager reports me an error:

Could not install package 'ChunkDecoder 1.0.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by jchristn** [comment]
Ah, I need to retarget ChunkDecoder to include 4.6.2. Great catch, I will get to this right away!

**Comment by jchristn** [comment]
Hi Timur, thanks for pointing this out!  I just re-targeted the ChunkDecoder package to also include .NET 4.6.2 (see https://www.nuget.org/packages/ChunkDecoder/1.0.3).  I believe the issue should be resolved when the NuGet index is updated.  Please let me know if that isn't the case.  Have a great day!

**Comment by timur4000** [comment]
Hi Joel !

I have upgraded Watson Webserver to 2.1.2 in my project but after that there was quite a strange thing has been happened.
I started my application server based on Watson Webserver  2.1.2 and  so weird thing appeared. Watson Web server works but does not process any http-request from my desktop http-client. My http-client sends http-request and wait for reply very long time and then generates an exception kinda "I have no reply during so long time".
Then I rolled back to previous Watson Webserver 2.0.2 and voila - my project works as expected! 
What can be wrong witn 2.1.2 version?

**Comment by jchristn** [comment]
Hi @timur4000 :)  That's very interesting.  I've changed the ```Test.*``` projects to also target .NET Framework 4.6.2 so we can test this out.

Would you be able to clone the repo and build the ```Test.Default``` project?  If you run ```Test.Default.exe``` it will spawn Watson on ```127.0.0.1:9000```.  You can then hit that URL from Chrome, Postman, cURL, etc, to see if Watson is working.

Additionally, could you share with me:
1) Code that shows initialization of the ```Server``` class
2) Code that sets variables in the ```Server``` class, including callbacks and routes
3) A skeleton of the default request handler method you supply to Watson

I tested with .NET Framework 4.6.2 locally and I didn't identify an issue on my side.  Perhaps there is an issue that exists that I'm unable to duplicate or an issue specific to your environment?  Please let me know if you can provide the above information.

Cheers, Joel

**Comment by jchristn** [comment]
For reference, you should see something like the following in command prompt when running Test.Default:
```
C:\Code\WatsonWebserver-2.1\Test.Default\bin\Debug\net462>Test.Default.exe
Starting Watson Webserver on: http://127.0.0.1:9000
Command [? for help] > --- HTTP Request ---
08/01/2019 14:13:42 127.0.0.1:51019 to 127.0.0.1:9000
  GET / HTTP/1.1
  Full URL    : http://127.0.0.1:9000/
  Raw URL     : /
  Querystring :
  Useragent   : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 (Keepalive True)
  Content     :  (0 bytes)
  Destination : 127.0.0.1:9000
  Headers     :
    Upgrade-Insecure-Requests: 1
    DNT: 1
    Connection: keep-alive
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
    Accept-Encoding: gzip, deflate, br
    Accept-Language: en-US,en;q=0.9
    Host: 127.0.0.1:9000
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
  Data        : [null]
```

And in Chrome, when you go to ```http://localhost:9000/``` you should see:
```
Watson says hello from the default route!
```

**Comment by timur4000** [comment]
Here is an example of my code

**Comment by timur4000** [comment]
[MySolution.zip](https://github.com/jchristn/WatsonWebserver/files/3457477/MySolution.zip)

Here is an example of how I use it.

**Comment by jchristn** [comment]
Thanks @timur4000 - should I be looking at ProjectStandard or ProjectApplicationServer?

**Comment by timur4000** [comment]
ProjectApplicationServer

**Comment by jchristn** [comment]
Thanks @timur4000 - the implementation looks good (and I like how you've implemented some things such as adding a wrapper around route creation).

Could you add logging statements into some of your routes to make sure they are entered when using v2.1.2?  I'd do it, but the solution won't compile for me.  

Also could you try the ```Test.Default``` project and make sure it works on your end?  Thanks!

**Comment by timur4000** [comment]
Could not get to work Test.Default instantly,
but I created a new console project based on NET Framework 4.6.2
and just replace default Program.cs to your Program.cs from test.

if I start exe file from FAR-manager it works

![test1](https://user-images.githubusercontent.com/42274107/62312025-8c202b00-b4a6-11e9-90ec-41b888e4cef3.png)

If I start it from Visual Studio 2017 (start without debugging) the server is not listening

![test2_VS_Start_button](https://user-images.githubusercontent.com/42274107/62312059-a8bc6300-b4a6-11e9-9220-938d66661dcb.png)

**Comment by jchristn** [comment]
Weird.  This sounds like it may be a user permissions issue.  I've noticed that when using 127.0.0.1 any user can start it, unless the port number is <1024.  Can you try running your app with elevated privileges and see if that makes a difference?  And what is the listener hostname you are specifying?

**Comment by jchristn** [comment]
Nevermind, looks like you are using 127.0.0.1 and port 9000.  Do you have another instance of it running in another window or anything?  

It may be helpful to do ```netstat -a -n -o``` from command prompt before running to see if anything is already listening on 9000, and then do again after you start Watson to see if it's listening there.

**Comment by timur4000** [comment]
if I execute VS2017 as administrator
![start_as_admin](https://user-images.githubusercontent.com/42274107/62366012-1ddb7700-b53f-11e9-8942-a44cef5d7a3e.png)
your test works

**Comment by timur4000** [comment]
Nevertheless problem in my project remains.
I upgraded my project to Watson Webserver 2.1.3
In route handlers I set callings of log messages.
When I execute my client application I see that client does not get reply from watson webserver.
In server side no any log messages were executed as if server ignores any http-request.
When I roll back to Watson 2.0.2 - all things works ok.

**Comment by jchristn** [comment]
Thanks @timur4000 - I'm going to build a single .CS file that mimics your setup in the next day.  Would you be willing to download (I'll put it on gist), add NuGet for Watson, and test it?  

There definitely seems to either be a user issue (runs as admin and not as a regular user) for you and it seems like it's isolated to 2.1.3, and additionally, an issue where it doesn't seem to work at all for you in 2.1.3.

If you would be willing to test the file, the script would be to:
- Compile with Watson 2.0.2, run as standard user, check for a response on various URLs, and show the output of ```netstat -a -n -o```
- Compile with Watson 2.0.2, run as administrator, check for a response on various URLs, and show the output of ```netstat -a -n -o```
- Compile with Watson 2.1.3, run as standard user, check for a response on various URLs, and show the output of ```netstat -a -n -o```
- Compile with Watson 2.1.3, run as administrator, check for a response on various URLs, and show the output of ```netstat -a -n -o```

I can also add more verbosity into the next version of Watson and a logging method that can be overridden (to use your own logger).

Would you be willing to test that out?  Cheers

**Comment by jchristn** [comment]
Hi @timur4000 I just tested this with both Watson 2.0.2 and Watson 2.1.3 using the default route, one of the static routes from your code, and one of the dynamic routes.  In both cases, whether admin/normal user, the requests were going through successfully.  

Sample screenshot here, 2.0.2 using default route under a normal user:
![watson2 0 2-normaluser](https://user-images.githubusercontent.com/1421081/62391891-dd6a0200-b51a-11e9-99aa-f56f9dbe0f72.png)

2.1.3 using dynamic route under a normal user: 
![watson2 1 3-dynamic-normaluser](https://user-images.githubusercontent.com/1421081/62391916-eb1f8780-b51a-11e9-860e-386d5c115fae.png)

The file I tested with is here, could you give it a test on your end with both Watson 2.0.2 and 2.1.3?  Definitely want to get to the bottom of this with you!

https://gist.github.com/jchristn/5ad1d74fd29bf824f406aca2f8a35430

**Comment by timur4000** [comment]
1. Compile with Watson 2.0.2, run as standard user, check for a response on various URLs, and show the output of netstat -a -n -o

Test works OK

  TCP    127.0.0.1:9000         0.0.0.0:0              LISTENING       4
  TCP    127.0.0.1:49260        0.0.0.0:0              LISTENING       2664
  TCP    127.0.0.1:50911        0.0.0.0:0              LISTENING       2868
  TCP    127.0.0.1:64245        127.0.0.1:9000         TIME_WAIT       0


2. Compile with Watson 2.0.2, run as administrator, check for a response on various URLs, and show the output of netstat -a -n -o

Test works OK

  TCP    127.0.0.1:9000         0.0.0.0:0              LISTENING       4
  TCP    127.0.0.1:9000         127.0.0.1:64254        ESTABLISHED     4
  TCP    127.0.0.1:9000         127.0.0.1:64310        ESTABLISHED     4
  TCP    127.0.0.1:9000         127.0.0.1:64311        ESTABLISHED     4
  TCP    127.0.0.1:49260        0.0.0.0:0              LISTENING       2664
  TCP    127.0.0.1:50911        0.0.0.0:0              LISTENING       2868
  TCP    127.0.0.1:64254        127.0.0.1:9000         ESTABLISHED     3844
  TCP    127.0.0.1:64278        127.0.0.1:9000         TIME_WAIT       0
  TCP    127.0.0.1:64310        127.0.0.1:9000         ESTABLISHED     3844
  TCP    127.0.0.1:64311        127.0.0.1:9000         ESTABLISHED     3844



3.  Compile with Watson 2.1.3, run as standard user, check for a response on various URLs, and show the output of netstat -a -n -o

Compiled with Watson 2.1.4 (because I did not save Watson 2.1.3 package)

Test works OK

  TCP    127.0.0.1:9000         0.0.0.0:0              LISTENING       4
  TCP    127.0.0.1:9000         127.0.0.1:64518        ESTABLISHED     4
  TCP    127.0.0.1:9000         127.0.0.1:64521        ESTABLISHED     4
  TCP    127.0.0.1:9000         127.0.0.1:64522        ESTABLISHED     4
  TCP    127.0.0.1:49260        0.0.0.0:0              LISTENING       2664
  TCP    127.0.0.1:50911        0.0.0.0:0              LISTENING       2868
  TCP    127.0.0.1:64518        127.0.0.1:9000         ESTABLISHED     3844
  TCP    127.0.0.1:64521        127.0.0.1:9000         ESTABLISHED     3844
  TCP    127.0.0.1:64522        127.0.0.1:9000         ESTABLISHED     3844
  TCP    127.0.0.1:64523        127.0.0.1:9000         TIME_WAIT       0


4. Compile with Watson 2.1.3, run as administrator, check for a response on various URLs, and show the output of netstat -a -n -o

Compiled with Watson 2.1.4

Test works OK

  TCP    127.0.0.1:9000         0.0.0.0:0              LISTENING       4
  TCP    127.0.0.1:9000         127.0.0.1:64550        ESTABLISHED     4
  TCP    127.0.0.1:9000         127.0.0.1:64551        ESTABLISHED     4
  TCP    127.0.0.1:9000         127.0.0.1:64552        ESTABLISHED     4
  TCP    127.0.0.1:49260        0.0.0.0:0              LISTENING       2664
  TCP    127.0.0.1:50911        0.0.0.0:0              LISTENING       2868
  TCP    127.0.0.1:64523        127.0.0.1:9000         TIME_WAIT       0
  TCP    127.0.0.1:64550        127.0.0.1:9000         ESTABLISHED     3844
  TCP    127.0.0.1:64551        127.0.0.1:9000         ESTABLISHED     3844
  TCP    127.0.0.1:64552        127.0.0.1:9000         ESTABLISHED     3844
  TCP    127.0.0.1:64553        127.0.0.1:9000         TIME_WAIT       0

**Comment by timur4000** [comment]
After testing I upgraded my project to Watson 2.1.4 and I found the problem remained.

I was trying to connect to my app server via my desktop client but had failed. 
After that failing I executed netstat and here is what it shows (I changed my real IP in this output log but it does not matter as far as I know):

I executed server and client on the same host = MyHostAddress

Watson Webserver port = 17000
ssl enabled = true


example 1

  TCP    MyHostAddress:17001     0.0.0.0:0              LISTENING       4
  TCP    MyHostAddress:17001     MyHostAddress:64726     CLOSE_WAIT      4
  TCP    MyHostAddress:17001     MyHostAddress:64738     ESTABLISHED     4
  TCP    MyHostAddress:64726     MyHostAddress:17001     FIN_WAIT_2      20908
  TCP    MyHostAddress:64738     MyHostAddress:17001     ESTABLISHED     3844


example 2


  TCP    MyHostAddress:17001     0.0.0.0:0              LISTENING       4
  TCP    MyHostAddress:17001     MyHostAddress:65379     CLOSE_WAIT      4
  TCP    MyHostAddress:65379     MyHostAddress:17001     FIN_WAIT_2      12080

**Comment by timur4000** [comment]
And, what I wanted to say else, nothing so matter, just I'm thinking out loud
I noticed that the empty <<catch block>> repeatedly appears in your source file WatsonWebserver.cs 
I just thinked that it will be little easier to find some problem if "catch block" anyhow reports about it.

**Comment by timur4000** [comment]
The initial problem also did not disappear.
I still cannot directly upgrade Watson Webserver via Nuget Package Manager UI because an error appears:
"Could not install package 'ChunkDecoder **1.0.2**'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

To workaround this annoying feature first I install ChunkDecoder **1.0.3** (not 1.0.2 did you noticed that?) and after that I am able to upgrade my project to last version of Watson Webserver.

**Comment by jchristn** [comment]
Hi @timur4000 yes that's correct, ChunkDecoder 1.0.3 was simply a retargeting to also include .NET Framework 4.6.2.  NuGet won't let me go back and edit dependencies on published versions of packages unfortunately, so the issue will remain with Watson 2.0.2.  Your workaround was perfect (upgrading ChunkDecoder).  

The empty catch blocks are there to not disturb the connection loop.  I have yet to add a method that will allow Watson to propagate errors.  I was planning to do that this weekend, and that might give better visibility into what's happening in your case.

I didn't realize you were using SSL.  This adds another dimension to the troubleshooting, because the connection could be stuck prior to, during, or after decryption.  While I add logging methods that can be implemented for Watson, could you add a static loopback URL to your server that always returns 200 with no data, i.e. ```return new HttpResponse(req, 200, null);``` for something like ```GET /loopback```?  It would be good to see if even something that simple responds back, since the test with 2.1.3 using the file I provided seemed to work.

We could also modify the file I sent in gist to use SSL, using your certificate, and see if it still works.  We'd have to register the SSL certificate with that particular port using ```netsh``` if we wanted to test that.  So I think it would be easier to add a loopback GET API or something to your existing code.  

Would you be willing to give that a try?

Also if you could, while 2.1.3 is running, please try running:
```
curl -i https://<yourhostname>:<yourport>/<yourURL>
```

Specifically I'd like to see if anything in the HTTP stack is listening and responding before it gets to your code, when using 2.1.3.  

Hope you're having a good day and thanks!

**Comment by timur4000** [comment]
since it happened that latest version is 2.1.4 let me work with it

**Comment by timur4000** [comment]
![curl_ssl](https://user-images.githubusercontent.com/42274107/62412163-33f44080-b5ee-11e9-852e-a98d3ccd04f0.png)

**Comment by timur4000** [comment]
> We could also modify the file I sent in gist to use SSL, using your certificate, and see if it still works
yeah I've already done it with 2.1.4 version (little modification of your test file from gist) - GET method works, default handler works 
but POST method failed because curl does not like my self signed certificate.

**Comment by jchristn** [comment]
Could you try with ```curl -k``` or ```curl --insecure```?  That should ignore the certificate check.

**Comment by jchristn** [comment]
BTW I'm creating a new version that will include logging callbacks so that we can propagate log messages from Watson into your app.  Stay tuned, working on this now.

**Comment by timur4000** [comment]
Joel, it seems I catch my problem.
It is my local problem, not your code.
This is my problem of deployment!!!
Assembly of my ProjectApplicationServer behaves so strange way that ChunkDecoder.dll does not come into assembly of ProjectApplicationServerUI.
I thought that ChunkDecoder.dll should automatically come with WatsonWebserver.dll but it does not happen (I dunno why?)
I noticed it just right now!
When I copy manually this ChunkDecoder.dll to final release of ProjectApplicationServerUI - all works fine !!!
sorry for inconvenience
you wasted for my problem so much time!

**Comment by timur4000** [comment]
But, of course It will be better If Watson notice that problem earlier than me and gives me a hint :-)
excuse me for inconvenience
Issue may be closed

**Comment by jchristn** [comment]
Hi @timur4000 you did not waste my time :) I'm glad to help!  Because of your feedback I'm adding events/callbacks right now into the code.  Will be pushing a build and NuGet package with that shortly and update this thread prior to closing.  Would love to get your feedback on it.  

On another note, I'm really glad you found the issue and got it working!!

**Comment by jchristn** [comment]
Added callbacks in this commit: https://github.com/jchristn/WatsonWebserver/commit/7f58c11b6430385229db706f0d640efa8c737863

Pushed NuGet v2.1.5 moments ago.

Cheers
