### ISSUE TITLE
Issue Hosting Images Larger Than ~200MB

### ISSUE THREAD

**Issue by ekarkosApollo** [jchristn/WatsonWebserver#23]
Watson Version: 1.2.11
.NET Framework: 4.6
Issue:
I am building an application which is meant to host up files to be uploaded to a web interface. Recently we were running tests with large .tif files and we noticed the application would hang when we tried to access the content route associated with that image. For example, the user would select an image which would get copied to a cache folder next to the .exe which is where the image would get hosted from (127.0.0.1/img/testimage.tif) whenever we try to access this URL the application hangs and we have to force exit. We noticed that with 175MB images it's able to chug through but once we go past 200MB images we start experiencing this issue. Is this package capable of hosting up such large files?

**Comment by jchristn** [comment]
Hi @ekarkosApollo yes it is - are you settings ```Server.ReadInputStream = false``` and then using ```HttpRequest.DataStream``` and ```HttpRequest.ContentLength```, or are you using ```HttpRequest.Data```?

**Comment by ekarkosApollo** [comment]
I was not able to find the `Server.ReadInputStream` setting, it may be because I am on an older version. I believe we are just using `HttpRequest.Data`, however we are not responding to the HttpRequest with the image data, we are simply copying it into a directory and setting that as an endpoint where the other application can access it along the lines of `server.AddContentRoute("/img/" + fileName)` and that URL then gets handed off to the other application which handles uploading.

**Comment by jchristn** [comment]
Ah ok, I see what's happening.

```ContentRouteProcessor.cs``` upon ```GET``` is reading the file info memory rather than returning the stream.  

So we'll need to do two things.

1) I'll need to amend the method to support sending a stream back to Watson, which will eliminate the need to load the entire file info memory.

2) I'll have to ask you to set the ReadDataStream variable to false on your side.  

I should be able to get to this today or tomorrow, hopefully that timeline will be ok for you?

Cheers, Joel

**Comment by jchristn** [comment]
I had a few minutes and think I have this knocked out.  Tested both with streams and with byte arrays and the logic is working and disposing of streams appropriately.  NuGet v2.1.3 will be going live shortly (https://www.nuget.org/packages/Watson/2.1.3) and the commit can be found here: https://github.com/jchristn/WatsonWebserver/commit/39baf658b70137c802041468b364d8e9686e8b29

Could you test on your end by adding ```Server.ReadInputStream = false```?  Thanks!

**Comment by ekarkosApollo** [comment]
Awesome, I will work on updating our application to the newest version, I will need some time but I will keep you updated.

Thanks so much for the quick responses and resolution.

**Comment by jchristn** [comment]
My pleasure!  Please re-open or file another issue if there are problems.  Cheers

**Comment by ekarkosApollo** [comment]
This update seemed to fix the issue we were having with large files thank you so much!

I don't know if you want a separate issue opened for this, but we are now seeing a problem with getting data out of a POST.

Whenever we receive a POST the data that used to be contained in `request.Data` is null. Do the 2.0.x+ versions of this package get data from POSTs differently now?

**Comment by ekarkosApollo** [comment]
For reference I am currently on version 2.1.3 targeting .NET framework 4.6.2

**Comment by jchristn** [comment]
Hi Eric if you have ReadStream set to true on the server the request body will be in HttpRequest.DataStream and HttpRequest.ContentLength will be set.
