### ISSUE TITLE
Disable Log Messages

### ISSUE THREAD

**Issue by Tutch** [jchristn/WatsonWebserver#3]
Maybe I've missed it, but is there a way to disable messages printed to console? With some very large requests being printed to console, the application is being delayed a little bit.

**Comment by Tutch** [comment]
I just realized server has "debug" as the last parameter. If someone has the same problem, setting it to false disable all console messages but the very first one that informs that the server is up.

**Comment by jchristn** [comment]
Hi @Tutch, glad you found those!  I was just about to respond.  Hope you have a great day!
