### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by chutch1122** [jchristn/WatsonWebserver#30]
Would it be possible to remove this welcome message or allow it to be optional?

https://github.com/jchristn/WatsonWebserver/blob/ff0f590e077e95cdda32ff2e659f4f20c40a91f6/WatsonWebserver/WatsonWebserver.cs#L214-L223

**Comment by jchristn** [comment]
Yeah, really doesn't need to be there, does it?  

NuGet v3.0.3 published with this change: https://www.nuget.org/packages/Watson/3.0.3 (give it 5-10 mins to publish)

Commit: https://github.com/jchristn/WatsonWebserver/commit/08605c9e004602114d298aaab66250328ecb6904

Cheers, Joel

**Comment by chutch1122** [comment]
Wow, that was quick. Thanks!
