### ISSUE TITLE
Cant acces server from anywhere but pc its running on

### ISSUE THREAD

**Issue by maetiskou** [jchristn/WatsonWebserver#31]
I've successfully created server which works perfectly fine on localhost until i try to connect to it from any other computer in network...

```
static void Main(string[] args)
        {
            Server server = new Server(_hostname, _port, false, DefaultRoute);
            Database database = new Database();

            server.AccessControl.Mode = AccessControlMode.DefaultPermit;

            for (; ; )
            {
                switch (Console.ReadLine())
                {
                    default:

                        break;
                    case "exit":
                        return;
                }
            }
        }

public static async Task DefaultRoute(HttpContext context)
        {
                context.Response.StatusCode = 200;
                await context.Response.Send("Succesful Request");
                return;
        }
```

Database class does communication with mysql database stuff..

I've created exception in firewall and i've tried running program with admin privileges..

**Comment by jchristn** [comment]
Hi @maetiskou on which hostname and which port number are you listening?  Are you using an IP address or a hostname for ```_hostname```?  When trying to connect from a client, are you using the IP address or hostname?  There has to be an explicit match between what you have for hostname and what comes in on the request (this is a restriction in the underlying http.sys).

Administrator is required if you use a port number under 1024, or, if you use ```*``` or ```+``` as the hostname, which will route any request on any DNS hostname/IP address to this instance (also making it a helpful debugging tool).

Could you try with ```*``` or ```+``` as the hostname in your constructor?

Thanks, Joel

**Comment by jchristn** [comment]
Hi @maetiskou did this help you?  Cheers

**Comment by jchristn** [comment]
Please reopen if the issue persists after trying the above.

**Comment by maetiskou** [comment]
Hi @jchristn i've tried all of the above before as i've seen it in other issues and nothing worked for me. 

Nonetheless i am using .Net HttpListener instead as it was just enough to suit my needs..

Problem was for sure somewhere in my network or router settings anyway... But thanks for the help.
