### ISSUE TITLE
RunSynchronously may not be called on a task that has already completed

### ISSUE THREAD

**Issue by at1993** [jchristn/WatsonWebserver#34]
From the Test.Events sample

The WatsonWebserver seems to trip on System.InvalidOperationException every time a GET request comes in. The error occurs in the AcceptConnections in WatsonWebserver.cs

 #region Default-Route
 _DefaultRoute(ctx).RunSynchronously();  <-- error here
return; 
#endregion 

ResponseSent event was never fired.

**Comment by jchristn** [comment]
Oooh, ouch.  Thanks for sending this.  Just confirmed this and will investigate!

**Comment by jchristn** [comment]
Hi @at1993 I confirmed that the ```ResponseSent``` event never fires but am unable to reproduce the ```InvalidOperationException``` when a GET request comes in.  Can you provide steps to reproduce?
![image](https://user-images.githubusercontent.com/1421081/72468385-e3cefc00-3791-11ea-966d-e192681b71c6.png)

**Comment by at1993** [comment]
Thanks for looking into the problem so promptly. The error may have suppressed when you test it in released mode. I tried it in debug mode via Visual Studio 2019.
![exception](https://user-images.githubusercontent.com/11742960/72469563-a7a99480-37ad-11ea-9199-1d9e1b73cf54.png)

**Comment by jchristn** [comment]
Thanks @at1993 - so this issue is not limited to just the ```Test.Events``` project, but any project including ```Test.Default``` (just confirmed).  

So there are two issues:

1) Even though the requests are being responded to and handled by the default route, somehow an ```InvalidOperationException``` is being thrown, and
2) The ```ResponseSent``` callback is never being called

Can you confirm that requests are being handled as expected by your code aside from these two issues?  Thanks!

**Comment by jchristn** [comment]
For issue #1, changing from ```.RunSynchronously()``` to ```.Wait()``` resolves the issue.

For issue #2, I'll need to amend ```HttpResponse``` to keep a flag indicating whether or not a response was sent, and check the flag at the end of ```ThreadPool.QueueUserWorkItem((c) => ...```

**Comment by at1993** [comment]
Thanks @jchristn .Wait() works for me. Just curious, Within the HttpResponse class, it does not signal (ResponseSent) at all when sending data is completed.

**Comment by jchristn** [comment]
Correct, I have to fix that :)  This and one other fix will be going into my next release.  Cheers!

**Comment by jchristn** [comment]
NuGet package published: https://www.nuget.org/packages/Watson/3.0.5

Commit: https://github.com/jchristn/WatsonWebserver/commit/657b75f15ca1de2c96a0dc667920ef04993618ab

Changes:
```
- Removed ThreadPool.QueueUserWorkItem in favor of unawaited Tasks
- Removed .RunSynchronously in favor of .Wait for the default route, thereby eliminating an InvalidOperationException (thank you @at1993)
- Properly firing ResponseSent events when the event callback is defined (thank you @at1993)
- Fixed an issue where the file path for content routes was not properly constructed (thank you @zaksnet)
- Added better documentation on event callbacks
```

Thanks for your help and re-open this issue if there are any problems!  Cheers
