### ISSUE TITLE
Folder path wrong

### ISSUE THREAD

**Issue by zaksnet** [jchristn/WatsonWebserver#35]
Hello,

I recently started using your library and had issues with `ContentRoutes` missing a slash at the end of the path. Example:

```CSharp
Server s = new Server("127.0.0.1", 9000, false, DefaultRoute);
s.ContentRoutes.Add("/someFolder/", true);
// ContentRouteProcessor.cs --> Process method creates the path as C:/myProjectsomeFolder instead of C:/myProject/someFolder.
```
I have fixed it by using a custom build with the following changes inside `ContentRouteProcessor.cs`:
```CSharp
var appDomain = AppDomain.CurrentDomain.BaseDirectory;

string filePath = ctx.Request.RawUrlWithoutQuery;
if (!String.IsNullOrEmpty(filePath))
{
        while (filePath.StartsWith("/") && (appDomain.EndsWith(@"\") || appDomain.EndsWith(@"/")))
        {
                filePath = filePath.Substring(1);
        }
}
```
The above checks for both slashes so it should be cross platform compatible. 
I would appreciate merging a fix for this or any similar implementation so that i don't have to compile my own every time you update. Thank you.

**Comment by jchristn** [comment]
Hi @zaksnet this is an excellent recommendation.  I'll include this in the next patch and comment with the commit and NuGet version.  Thanks!

**Comment by jchristn** [comment]
Hi @zaksnet this should also meet your needs.  Please confirm and I'll get a commit pushed and an update in NuGet.  

Primary goal: make sure the file path includes a slash character between the ```AppDomain.CurrentDomain.BaseDirectory``` and the relative path from the URL.

```
            string filePath = ctx.Request.RawUrlWithoutQuery;
            if (!String.IsNullOrEmpty(filePath))
            {
                while (filePath.StartsWith("/")) filePath = filePath.Substring(1); 
            }

            string baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
            while (baseDirectory.Contains("\\")) baseDirectory = baseDirectory.Replace("\\", "/");
            if (!baseDirectory.EndsWith("/")) baseDirectory += "/";

            filePath = baseDirectory + filePath;
            filePath = filePath.Replace("+", " ").Replace("%20", " ");
```

**Comment by jchristn** [comment]
NuGet package published: https://www.nuget.org/packages/Watson/3.0.5

Commit: https://github.com/jchristn/WatsonWebserver/commit/657b75f15ca1de2c96a0dc667920ef04993618ab

Changes:
```
- Removed ThreadPool.QueueUserWorkItem in favor of unawaited Tasks
- Removed .RunSynchronously in favor of .Wait for the default route, thereby eliminating an InvalidOperationException (thank you @at1993)
- Properly firing ResponseSent events when the event callback is defined (thank you @at1993)
- Fixed an issue where the file path for content routes was not properly constructed (thank you @zaksnet)
- Added better documentation on event callbacks
```

Thanks for your help and re-open this issue if there are any problems!  Cheers

**Comment by zaksnet** [comment]
> NuGet package published: https://www.nuget.org/packages/Watson/3.0.5
> 
> Commit: [657b75f](https://github.com/jchristn/WatsonWebserver/commit/657b75f15ca1de2c96a0dc667920ef04993618ab)
> 
> Changes:
> 
> ```
> - Removed ThreadPool.QueueUserWorkItem in favor of unawaited Tasks
> - Removed .RunSynchronously in favor of .Wait for the default route, thereby eliminating an InvalidOperationException (thank you @at1993)
> - Properly firing ResponseSent events when the event callback is defined (thank you @at1993)
> - Fixed an issue where the file path for content routes was not properly constructed (thank you @zaksnet)
> - Added better documentation on event callbacks
> ```
> 
> Thanks for your help and re-open this issue if there are any problems! Cheers

Wow, that was super fast! Thank you.
