### ISSUE TITLE
Exception event

### ISSUE THREAD

**Issue by zaksnet** [jchristn/WatsonWebserver#36]
Hello,
I'm getting the following exception when static routes are called: 
```
System.InvalidOperationException: RunSynchronously may not be called on a task that has already completed.
   at System.Threading.Tasks.Task.InternalRunSynchronously(TaskScheduler scheduler, Boolean waitForCompletion)
   at WatsonWebserver.Server.<>c__DisplayClass27_0.<AcceptConnections>b__0()
```
Minimal reproduction script:
```CSharp
        Server server = new Server("127.0.0.1", 9000, false, DefaultRoute);
        server.StaticRoutes.Add(HttpMethod.GET, "/test", test);
        server.Events.ExceptionEncountered = ExceptionEncountered;

        static async Task test(HttpContext ctx)
        {
            Console.WriteLine(ctx.ToString());
        }

        static bool ExceptionEncountered(string ip, int port, Exception e)
        {
            Console.WriteLine("ExceptionEncountered [" + ip + ":" + port + "]: " + Environment.NewLine + e.ToString());
            return true;
        }
```
I would guess thats a regression to:

> - Removed .RunSynchronously in favor of .Wait for the default route, thereby eliminating an InvalidOperationException (thank you @at1993)

**Comment by jchristn** [comment]
Thanks @zaksnet I have a fix I'm adding right now.  So sorry about that!  Give me 10min.

**Comment by jchristn** [comment]
Hi @zaksnet this should do it.

NuGet: https://www.nuget.org/packages/Watson/3.0.6
Commit: https://github.com/jchristn/WatsonWebserver/commit/e3ba228dd1800ee41f91743534f90b758349c32d

Leaving open for you to confirm.  Thanks!

**Comment by zaksnet** [comment]
> Hi @zaksnet this should do it.
> 
> NuGet: https://www.nuget.org/packages/Watson/3.0.6
> Commit: [e3ba228](https://github.com/jchristn/WatsonWebserver/commit/e3ba228dd1800ee41f91743534f90b758349c32d)
> 
> Leaving open for you to confirm. Thanks!

Great! Seems to be good now, thanks!
