### ISSUE TITLE
Downloading files 500 error

### ISSUE THREAD

**Issue by zaksnet** [jchristn/WatsonWebserver#37]
Hello,

case 1) When downloading files, only one connection can download the same file. The next connection will get a 500 error ( some exception occurred ).

case 2) If a client is downloading a file and the client connection is closed, the file remains open and the next connection gets the 500 error again.

I didn't want to go through downloading the source code and compiling/testing again since you seem to be fixing and pulling fast and the error is obvious:

```CSharp
FileStream fs = new FileStream(filePath, FileMode.Open);
ctx.Response.StatusCode = 200;
ctx.Response.ContentLength = contentLength;
ctx.Response.ContentType = GetContentType(filePath);
await ctx.Response.Send(contentLength, fs);
return;
```

I assume all you have to do is `fs.close()` to close the files stream although i have not tested this. It should at least be enough for case 2.

**Comment by jchristn** [comment]
Hi @zaksnet no sweat, I will test this today and report back.  Thanks for letting me know!

**Comment by jchristn** [comment]
Quick question - are you experiencing this in a content route?

**Comment by jchristn** [comment]
I was able to reproduce this and fix it by changing the way I instantiated the FileStream object.  Will commit a new version right now and send the NuGet/commit links!
```
FileStream fs = new FileStream(filePath, FileMode.Open);
```
becomes
```
FileStream fs = new FileStream(filePath, FileMode.Open, FileAccess.Read);
```

**Comment by jchristn** [comment]
Try these, please close if this resolves the issue!  Cheers
NuGet 3.0.6.1: https://www.nuget.org/packages/Watson/3.0.6.1
Commit: https://github.com/jchristn/WatsonWebserver/commit/095537ea18fca04782a6392482df29dedbc2ea58

**Comment by zaksnet** [comment]
> Try these, please close if this resolves the issue! Cheers
> NuGet 3.0.6.1: https://www.nuget.org/packages/Watson/3.0.6.1
> Commit: [095537e](https://github.com/jchristn/WatsonWebserver/commit/095537ea18fca04782a6392482df29dedbc2ea58)


Nope, same error:

![Screenshot_1](https://user-images.githubusercontent.com/1850856/73118249-5b531700-3f5a-11ea-8918-63e186b8763b.png)

![Screenshot_2](https://user-images.githubusercontent.com/1850856/73118273-8f2e3c80-3f5a-11ea-88d5-8aa7364d8a0f.png)

**Comment by zaksnet** [comment]
I think adding `FileShare.ReadWrite` did the trick:

```CSharp
FileStream fs = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
```

**Comment by jchristn** [comment]
Hi @zaksnet - is something else concurrently writing to the file while Watson is reading it?  Using ```FileShare.ReadWrite``` may not be safe for general cases so I hesitate to add that change.

I tried with a large file on my end (to make sure the connections stayed open) and with the change I made I had no issue scaling up to 10 clients (no exceptions, all were able to download the file).

Thanks for sending the commit over!  It seems there are two big changes:
1) ```using (FileStream fs = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))``` (discussing here)
2) use of ```.ConfigureAwait(true)``` which is new to me :) so I'll investigate this now!

Please let me know on the item above.  I'm wondering if you had a writer working in parallel or if perhaps there's some file system permissions/configuration issue?

**Comment by jchristn** [comment]
Another thing I could do is have an enum that dictates what level of FileShare mode to use by default in the content route processor.  That way you could set it to whatever you like (the last thing I want to do is have you have to update and recompile every time there is a change!)

That would probably satisfy most if not all use cases, agreed?

**Comment by zaksnet** [comment]
> Another thing I could do is have an enum that dictates what level of FileShare mode to use by default in the content route processor. That way you could set it to whatever you like (the last thing I want to do is have you have to update and recompile every time there is a change!)
> 
> That would probably satisfy most if not all use cases, agreed?

Hi @jchristn ,Its ok no need over complicate this, i only care that it works. Let me see i might have missed something last time. Will check 3.6.1 again and come back to you.

**Comment by jchristn** [comment]
Sounds good @zaksnet - FWIW, a ```Settings``` object is long overdue in Watson anyway to provide a standard way of making things like this configurable, so I'm happy to do it.

**Comment by zaksnet** [comment]
> Sounds good @zaksnet - FWIW, a `Settings` object is long overdue in Watson anyway to provide a standard way of making things like this configurable, so I'm happy to do it.

Alright if its not trouble then go for it, should be good to have it! After removing all references of the library in my PC (nugget seems to store these all over the place) and reinstalling now it seems to be working fine with your commits. Thanks again and sorry for the trouble!

**Comment by zaksnet** [comment]
By the way, if a connection is closed while a transfer is happening i get an exception at the server:
```
System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.
. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine.

  at System.Net.Sockets.Socket.EndSend (System.IAsyncResult asyncResult) [0x00012] in <8c9baba7add14c22be562e4c18e5738f>:0
  at System.Net.Sockets.NetworkStream.EndWrite (System.IAsyncResult asyncResult) [0x00057] in <8c9baba7add14c22be562e4c18e5738f>:0
   --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.EndWrite (System.IAsyncResult asyncResult) [0x0009b] in <8c9baba7add14c22be562e4c18e5738f>:0
  at System.Net.ResponseStream.EndWrite (System.IAsyncResult ares) [0x00051] in <8c9baba7add14c22be562e4c18e5738f>:0
  at System.IO.Stream+<>c.<BeginEndWriteAsync>b__58_1 (System.IO.Stream stream, System.IAsyncResult asyncResult) [0x00000] in <40b8b083f8564fad98f2f0a051f8ab78>:0
  at (wrapper delegate-invoke) System.Func`3[System.IO.Stream,System.IAsyncResult,System.Threading.Tasks.VoidTaskResult].invoke_TResult_T1_T2(System.IO.Stream,System.IAsyncResult)
  at System.Threading.Tasks.TaskFactory`1+FromAsyncTrimPromise`1[TResult,TInstance].Complete (TInstance thisRef, System.Func`3[T1,T2,TResult] endMethod, System.IAsyncResult asyncResult, System.Boolean requiresSynchronization) [0x00000] in <40b8b083f8564fad98f2f0a051f8ab78>:0
--- End of stack trace from previous location where exception was thrown ---

  at WatsonWebserver.HttpResponse.Send (System.Int64 contentLength, System.IO.Stream stream) [0x001b8] in <fb97c5c849f040b5817f9294a5720cad>:0
```
You might want to look into that.

**Comment by jchristn** [comment]
Thanks @zaksnet I will do that (both)!  Reopening so I can track on my end.

**Comment by jchristn** [comment]
Hi @zaksnet out of curiosity, how did you catch this?  I put try/catch around ```Response.Send``` and also in the content route processor, but I can't catch this, even if I ctrl-C on a cURL download of a large object.  Cheers

**Comment by zaksnet** [comment]
Hi @jchristn, exception event is giving it.

**Comment by jchristn** [comment]
Hi @zaksnet something interesting is happening when I test this.  You mentioned an IOException above - but in the disconnect case, I'm getting an HttpListenerException.  Could you verify with the latest code that it is consistent with what you see on your side?  I'd hate to not have a handler for IOException if that's the cause, but I suspect the IOException was caused by too many FileStreams competing for full access to a file while it was locked, and that the disconnection exception was actually an HttpListenerException.

**Comment by jchristn** [comment]
Also I'm adding another event callback for cases where the requestor disconnects unexpectedly.

**Comment by zaksnet** [comment]
Hi @jchristn , the exact process i follow is:
1) Start the WastonWebServer
2) In Chrome, i start downloading a large file (Only one, if i try download more it works as expected)
3) In Chrome i cancel the download and i get the following exception in the console:
![Screenshot_3](https://user-images.githubusercontent.com/1850856/73139689-41f4bc80-4079-11ea-8b5b-659ddd0b9409.png)

If i try to download more than one file it works, i'm not getting any errors this time but each download i cancel i get the exception. I dont think i'v seen an HttpListenerException exception so far.
I'v also deleted all references of WatsonWebServer.dll on my PC and reinstalled it to make sure the correct version is installed so i'm afraid its an IOException for me.

**Comment by jchristn** [comment]
Thanks @zaksnet this is extremely helpful.  I was testing using cURL and using ctrl-C to abort.  So this gives me another way to test and validate.  Thanks again

**Comment by jchristn** [comment]
So strange.  When I cancel a download in Chrome, the exception is being caught by the new ```RequestorDisconnected``` event, which is catching on ```HttpListenerException```.  

I'm looking for a reference on the possible ```HResult``` values for ```IOException``` so I can accurately filter on socket-related exceptions and handle them the same way as ```HttpListenerException```.  Stay tuned.

**Comment by jchristn** [comment]
Are you running a standalone application with Watson or are you running one of the test projects directly from within Visual Studio?

**Comment by jchristn** [comment]
Ok I think I've landed on a solution.  I can't replicate what you're experiencing with IOException and an inner exception of SocketException, but I'll publish this and see if it resolves the matter.  Note that you'll want to implement the new event callback ```RequestorDisconnected``` and note that all of the event callbacks have a different signature (they are now ```Action``` vs ```Func```, so the return type of your implementation can just be ```void```).

Publishing, one sec.

**Comment by jchristn** [comment]
Here it is!

Nuget: https://www.nuget.org/packages/Watson/3.0.7
Commit: https://github.com/jchristn/WatsonWebserver/commit/4d9993804591155b20c80039c7454125487a7f96

Here is the implementation of the ```RequestorDisconnected``` event callback (note all have return type of 'void' now):

``` 
        static void RequestorDisconnected(string ip, int port, string method, string url)
        {
            Console.WriteLine("RequestorDisconnected [" + ip + ":" + port + "] " + method + " " + url); 
        } 
```

Please let me know if your situation is caught using the ```RequestorDisconnected``` event callback once you upgrade to 3.0.7!

**Comment by zaksnet** [comment]
Thank you @jchristn ! Everything seems to be working good now. Cheers!

**Comment by jchristn** [comment]
Whew!  I'm glad it is being caught properly now.  Cheers @zaksnet thanks for all of your help.
