### ISSUE TITLE
Any way to listen on multiple ports at the same time?

### ISSUE THREAD

**Issue by winkmichael** [jchristn/WatsonWebserver#38]
Hello Joel,

I'm wondering if I am missing it, but I am not seeing a way to listen on multiple ports at the same time, any option here?

Thanks.
Mike

**Comment by jchristn** [comment]
Hi Mike, 

As of right now there isn't, but it would be easy enough for me to add another constructor that would allow you to supply a list of URIs.  Would that work for you?

Also which platform are you running on?  The support for multiple prefixes (listener URIs) was limited on non-Windows systems in my previous examinations.

Cheers
Joel

**Comment by winkmichael** [comment]
That would be super fantastic and very much appreciated! Linux primary for the program, and development ... sorry for being difficult (:

**Comment by jchristn** [comment]
You got it, I'll make that change.  Please note that it may throw exceptions if you try to open multiple listener endpoints on Linux though.  This link doesn't document this exact issue but gives some indication as to why it creates problems: https://github.com/dotnet/runtime/issues/21733

**Comment by jchristn** [comment]
Something like this I assume?

![image](https://user-images.githubusercontent.com/1421081/74398403-5c929980-4dcc-11ea-87ed-e71d9c294dff.png)

**Comment by jchristn** [comment]
Nuget package: https://www.nuget.org/packages/Watson/3.0.8
Commit: https://github.com/jchristn/WatsonWebserver/commit/c2aa397257598cb4f0f3b1b4e0ce2bdaa1be53e9

Here you go sir!  

Note there may be issues with using this on Linux (again it's underneath my code, so I can't do much about it).  Please re-open if any other issues!  

Cheers, Joel

PS thanks for making the project better!

**Comment by winkmichael** [comment]
Thanks for that. My project is built around .NET Framework 4.7.2 and no luck on Linux, not only do you not get multiple listeners you get no listeners. The link to the MS git project looks like a fix might be right around the corner, fingers crossed (: Thanks for your help, time and efforts yet again!

**Comment by jchristn** [comment]
My pleasure @winkmichael have a good one!

**Comment by winkmichael** [comment]
I know this is one is super simple to figure out, but just in case someone stumbles by this problem ... You can work around the .NET bug this way and not break the async methods;

```

static void Main(string[] args)
{
 List<int> Ports = new List<int>
 {
 8001,
 8002,
 8003
 };
 foreach(int port in Ports)
  {
  Thread watsonChildThread = new Thread(() => startWatsonThread(port));
  watsonChildThread.Start();
  }
}
static void startWatsonThread(int portObject)
 {
 var port = portObject;
 Server s = new Server("0.0.0.0", portObject, false, DefaultRoute);
 s.ContentRoutes.Add("/html/", true);
}
```

**Comment by jchristn** [comment]
Great point @winkmichael - you could even use ```Task.Run``` to kick them off with separate a ```CancellationToken``` for each or maintain a ```List<Task>``` to interact with them later.  The background tasks, each listening on a separate port, could also share the same event methods!  Thanks for bringing this up!  Cheers, Joel
