### ISSUE TITLE
Xamarin Android

### ISSUE THREAD

**Issue by Tutch** [jchristn/WatsonWebserver#4]
There's a compile error when trying to build a project for Xamarin Android. It's probably related to the System.Web library as seen [here](https://forums.xamarin.com/discussion/4316/could-not-load-assembly-system-web-error). 

You use it for the SerializeJsonBuiltIn function in WatsonCommons, but you already provide Newtonsoft.Json that also has serialization. Maybe you could provide a branch containing only Newtonsoft so the build for Android is possible? Thanks in advance!

>Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1391,2): error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Perhaps it doesn't exist in the Mono for Android profile?
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1391,2): error : File name: 'System.Web.Extensions.dll'
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1391,2): error :   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference, Mono.Cecil.ReaderParameters parameters) [0x000c2] in /Users/builder/data/lanes/4695/9dbc4c53/source/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:225 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1391,2): error :   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference) [0x00001] in /Users/builder/data/lanes/4695/9dbc4c53/source/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:175 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1391,2): error :   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver, System.Collections.Generic.ICollection`1[T] assemblies, Mono.Cecil.AssemblyDefinition assembly, System.Boolean topLevel) [0x00189] in /Users/builder/data/lanes/4695/9dbc4c53/source/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs:143 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1391,2): error :   at Xamarin.Android.Tasks.ResolveAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver) [0x001c5] in /Users/builder/data/lanes/4695/9dbc4c53/source/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs:88 
    0 Warning(s)
    1 Error(s)

**Comment by Tutch** [comment]
I managed to work around it by modifying your code.
- In HttpRequest and HttpResponse I swapped **HttpUtility.UrlDecode** for **System.Uri.EscapeUriString**
- Removed your built in functions for deserialization

There's the downside of not having built-in deserialization, but it's working just fine in Xamarin Android now :)

**Comment by jchristn** [comment]
Hi @Tutch thanks for filing these, I will be looking into them over the weekend!  Much appreciated!

**Comment by jchristn** [comment]
Hi @Tutch I'm merging this into master and will publish an updated NuGet package in a moment.  Thank you so much for making the changes and creating the pull request!

**Comment by jchristn** [comment]
Merged and updated to v1.2.2: https://github.com/jchristn/WatsonWebserver/commit/8175e5f6eac1d166f6c30411a4b80a73fe02021b

Thanks again!
