### ISSUE TITLE
HttpContext Request.QuerystringEntries Wrong

### ISSUE THREAD

**Issue by rangsutu88** [jchristn/WatsonWebserver#40]
hello,
i set up a test WatsonWebserver at 127.0.0.1:9000. and make below request to this sever.
"http://127.0.0.1:9000/hello?key=test//test"

but i capture the Request.QuerystringEntries. it receive the key parameter is "test/test". 1 "/" is missing.
What is problem?
Could someone advise.
Thanks

**Comment by jchristn** [comment]
Hi @rangsutu88 thanks for your note. I will look into it ASAP hopefully today. I have an idea where the issue is. Cheers Joel

**Comment by jchristn** [comment]
Hi @rangsutu88 - these are being URL decoded.  The ```/``` character is a ***reserved character*** which has to be encoded.  Please refer to p2.2 of the RFC: https://tools.ietf.org/html/rfc3986#page-12 (there's a healthy discussion about this on stackoverflow here: https://stackoverflow.com/questions/1455578/characters-allowed-in-get-parameter)

These are being processed and decoded by ```WebUtility.UrlDecode``` (see https://docs.microsoft.com/en-us/dotnet/api/system.net.webutility.urldecode?view=netcore-3.1) to accomplish this.  

Cheers, Joel

**Comment by rangsutu88** [comment]
hi @jchristn . 
I think this issue come from WatsonWebserver Request module. at below code
at the line 243 in HttpRequest.cs. Sorry if i'm wrong

```
region Process-Raw-URL-and-Populate-Raw-URL-Elements

                while (RawUrlWithoutQuery.Contains("//"))
                {
                    RawUrlWithoutQuery = RawUrlWithoutQuery.Replace("//", "/");
                }
```

**Comment by jchristn** [comment]
Hi @rangsutu88 that is being done over the URL, not the query string entries. The query string is handled by the decode function.

**Comment by rangsutu88** [comment]
hi @jchristn ,
Thank your for your explanation.
