### ISSUE TITLE
custom base directory for content routes

### ISSUE THREAD

**Issue by joreg** [jchristn/WatsonWebserver#41]
hei joel,

thanks for this superb library! only thing i seem to be missing so far is to be able to provide a custom directory for content routes. or is there a reason why this wouldn't make any sense?

**Comment by jchristn** [comment]
Hi @joreg thanks for the kind words!  

When you say a custom directory, may I ask to what you are referring?  

Here's an example using content routes; you can specify whatever directory you like in the first parameter passed to ```ContentRoutes.Add```.
```
Server s = new Server("127.0.0.1", 9000, false, DefaultRoute); 
s.ContentRoutes.Add("/", true);
s.ContentRoutes.Add("/html/", true);
s.ContentRoutes.Add("/large/", true);
s.ContentRoutes.Add("/img/watson.jpg", false);
```
Thanks!  ~Joel

**Comment by joreg** [comment]
i mean the base directory, that the contentroutes resolve towards. by deafult this seems to the location of the .exe, right? so if my program is

    c:\myapp\foo.exe

then the above example would resolve to 

    c:\myapp\img\watson.jpg

but what if i'd like it to resolve to 

    d:\mycontent\img\watson.jpg

**Comment by jchristn** [comment]
Hi @joreg that makes sense.  I tried to make it flexible by allowing you to specify entire directories in content routes as well as specific files using either relative or explicit paths. 

i.e. entire directory:
```
s.ContentRoutes.Add("/html/", true);
```

i.e. specific file:
```
s.ContentRoutes.Add("/img/watson.jpg", false);
```

I agree that having some concept of a 'base directory' is a good thing, but in so doing it would make it hard to then have a series of content routes that span different locations in the file system.  Would you agree?

**Comment by joreg** [comment]
`...but in so doing it would make it hard to then have a series of content routes that span different locations in the file system.`

not sure i quite understand that. because you have the same "problem" now, don't you? ie. allow to change the base path wouldn't change anything regarding this "problem", right?

just to clarify: i'm only talking about being able to override this line:

    string baseDirectory = AppDomain.CurrentDomain.BaseDirectory;

with a custom directory.

**Comment by jchristn** [comment]
Hi @joreg got it, thank you for clarifying.  This makes sense.

How would you feel about this as a solution: I can expose this as a public parameter off of ```WatsonWebserver.ContentRoutes``` and then have that pass through to ```ContentRouteProcessor```.  If someone attempts to set the value to null, I instead set it to its default value of ```AppDomain.CurrentDomain.BaseDirectory``` (to prevent people from shooting themselves in the foot).  i.e. they could set it to ```/```, that would be fine, but null would go back to base directory.  

What do you think?  Cheers, Joel

**Comment by joreg** [comment]
that sounds great!

**Comment by jchristn** [comment]
Hi @joreg please re-open if this solution is insufficient.  Thanks for the excellent enhancement request!  Cheers, Joel

NuGet v3.0.11: https://www.nuget.org/packages/Watson/3.0.11
Commit: https://github.com/jchristn/WatsonWebserver/commit/e704dc2627360a0a04cbe17bfadc9929ebd00bec
