### ISSUE TITLE
returning [id] to a string

### ISSUE THREAD

**Issue by winkmichael** [jchristn/WatsonWebserver#42]
Hello Joel,

Using a dynamic route I'd like to get the [id] from your main example. I don't seem to see anything in ctx.Request that would allow me to get that other than parsing the QueryString. 

Any chance there is another way?

Thanks for your time and help!

Snippet of your own code ...
```
s.DynamicRoutes.Add(HttpMethod.GET, new Regex("^/foo/\\d+$"), GetFooWithId);  
static async Task GetFooWithId(HttpContext ctx)
{
  ctx.Response.StatusCode = 200;
  await ctx.Response.Send("Hello from the GET /foo/[id] dynamic route!");
}
```

**Comment by jchristn** [comment]
Hi @winkmichael you are correct, you would need to parse the raw URL. The RawUrlEntries property may be helpful for this. Cheers, Joel

**Comment by winkmichael** [comment]
Thanks that works perfect.

One other question, two things that don't seem to work that worked since my latest update.

Again quoting your own code here;

```
static async Task DownloadChunkedFile(HttpContext ctx)
{
  using (FileStream fs = new FileStream("./img/watson.jpg" , FileMode.Open, FileAccess.Read))
  {
    ctx.Response.StatusCode = 200;
    ctx.Response.ChunkedTransfer = true;

    byte[] buffer = new byte[65536];
    int bytesRead = await fs.ReadAsync(buffer, 0, buffer.Length);
    if (bytesRead > 0)
    {
      // you'll want to check bytesRead vs buffer.Length, of course!
      ctx.Response.SendChunk(buffer);
    }
    else
    {
      ctx.Response.SendFinalChunk(buffer);
    }
  }

  return;
}
```
This will never result in the http session ending, but I am pretty sure it used to shutdown. Basically if I open http://127.0.0.1:9000/abcdef  I get the png file and it renders perfect but the browser keeps on spinning forever.

I made my own test here where I take the entire file into a byte array, just in case it was something about the FileStream I was overlooking.

Any suggestions as always are very much appreciated. Thanks in advance!

```

static async Task DefaultRoute(HttpContext ctx)
        {
            ctx.Response.StatusCode = 200;
            ctx.Response.ChunkedTransfer = true;
            byte[] jpeg = File.ReadAllBytes("test.jpeg");
            ctx.Response.SendChunk(jpeg);
            return;
}
```

**Comment by winkmichael** [comment]
Thanks, I just wrote out a long comment about some other issue, but I need either sleep or coffee. As Final is right in the key, anyhow. Thanks again for your help and prompt replies on this lovely project!

**Comment by jchristn** [comment]
My pleasure @winkmichael happy to help anytime.  I saw the comment about SendChunk vs SendFinalChunk; I assume that's the item to which you're referring.  Please do not hesitate to reach out if any issues!  Closing this one down for now.  Have a good night!
