### ISSUE TITLE
Dot Net Core support

### ISSUE THREAD

**Issue by CloudBranch** [jchristn/WatsonWebserver#45]
When is dot net core support coming?

By the way...Thank you for creating this awesome project. This should have way more stars. Very useful.

**Comment by jchristn** [comment]
Hi @CloudBranch thank you for your kind words!

I publish a single NuGet that contains both .NET Framework as well as .NET Standard, and use it in .NET Core projects all the time.  Was there something else that you were looking for beyond that?

Cheers, Joel

**Comment by jchristn** [comment]
Hi @CloudBranch please re-open if there is something needed beyond .NET standard.  It works in .NET Core use cases.  Cheers!
