### ISSUE TITLE
No way to catch port in use

### ISSUE THREAD

**Issue by at1993** [jchristn/WatsonWebserver#46]
In the AcceptConnections method, the httplisterner.Start method may fail (ex. port in use). Since the HttpListernerException is not signaled to the application. It is sometime difficult to figure out why the application is not working. In the meantime I added the try/catch around the _HttpListener.Start() method

try
{
    _HttpListener.Start();
}
catch (HttpListenerException er)
{
    Events.ExceptionEncountered?.Invoke(null, 0, er);
}

@jchristn, am I correct or am I missing something? 

Thanks.

**Comment by jchristn** [comment]
Hi @at1993 - does the ```ServerStopped``` event fire correctly?  We could definitely fire the ```ExceptionEncountered``` event there too if it's of value.

**Comment by at1993** [comment]
Thanks @jchristn for the quick reply. Yes, the ServerStopped event was fired correctly.  It would be nice to know why the server stopped right after it was started. I really like the second idea where you make an explicit.Start() method. That will awesome. Thank you.

**Comment by jchristn** [comment]
Awesome.  I'll probably throw the exception as well in addition to firing the event.  Will add it to my list (will be a breaking change so I'll bump to v3.2)

**Comment by at1993** [comment]
Thank you!

**Comment by jchristn** [comment]
Starting work on this now

**Comment by jchristn** [comment]
Hi @at1993 please let me know if this works out for you (please feel free to close the issue if it does).

Note you'll have to call ```Start()``` now (and there's also a ```Stop()``` API)

NuGet v3.2.0: https://www.nuget.org/packages/Watson/3.2.0
Commit: https://github.com/jchristn/WatsonWebserver/commit/743cce1374b2f1ae537ec8324c601d3ca366634f

**Comment by jchristn** [comment]
Closing, please re-open if issues
