### ISSUE TITLE
Throttling Number of active connection - Information

### ISSUE THREAD

**Issue by yashhema** [jchristn/WatsonWebserver#48]
Hello,
Is it possible to throttling number of active connection 
i want to use droplet which is quite small in resources, and I know that it can handle only x number of active request, by using above parameter I can just drop request if number of active request become more than that.

**Comment by jchristn** [comment]
Hello @yashhema there is no capability today in the library to do this.  You could however maintain a variable in your application that is incremented each time a connection is being serviced and decremented thereafter, and you could configure the ```PreRoutingHandler``` to check this variable and either permit (```return false```) or deny/terminate the connection (```return true```).
```
        /// <summary>
        /// Function to call prior to routing.  
        /// Return 'true' if the connection should be terminated.
        /// Return 'false' to allow the connection to continue routing.
        /// </summary>
        public Func<HttpContext, Task<bool>> PreRoutingHandler = null;
```

**Comment by jchristn** [comment]
Hi @yashhema please try v3.3.0.2 and re-open if any issues.

NuGet: https://www.nuget.org/packages/Watson/3.3.0.2
Commit: https://github.com/jchristn/WatsonWebserver/commit/91043a5fd96cf833313833d585960d4837c26ecb

Usage:
```
_Server = new Server("127.0.0.1", 8000, false, DefaultRoute);
_Server.MaxRequests = 5;
_Server.Start();

static async Task DefaultRoute(HttpContext ctx)
{
  // your code here
}
```

Implementation: if the private ```_RequestCount``` exceeds ```MaxRequests```, ```await _HttpListener.GetContextAsync();``` is not entered.  Instead the server will pause for 100ms and restart the loop.

Cheers, Joel
