### ISSUE TITLE
Use with TelegramBot

### ISSUE THREAD

**Issue by absid89** [jchristn/WatsonWebserver#50]
I cant use WatsonWebserver with TelegramBot (https://github.com/TelegramBots/Telegram.Bot), at same time (watson need Newtonsoft.Json v12, telegrambot v11). Nuget packages installing correctly but after start application, i get exception:

Could not load file or assembly "Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

any ideas how fix this? thx for any help

**Comment by jchristn** [comment]
Hi @absid89 you can clone and modify the project to use the same version of Newtonsoft as the other package.  Then build and include the locally built DLL into your project.

**Comment by absid89** [comment]
thx, resolve this problem, rebuild telegrambot with needed package
