### ISSUE TITLE
hosting watsonwebserver on windows dervice

### ISSUE THREAD

**Issue by KKoustas** [jchristn/WatsonWebserver#6]
Static root does not work because root directory is c:\windows\system32
in ContetRouteProcesson.cs after line 44 add the following
44)  if (!String.IsNullOrEmpty(filePath) && filePath.StartsWith("/")) filePath = filePath.Substring(1);
45)  filePath = AppDomain.CurrentDomain.BaseDirectory + filePath;

then works like a charm :)

**Comment by jchristn** [comment]
Thank you @KKoustas looking at this now!

**Comment by jchristn** [comment]
Thanks so much for the fix @KKoustas this is perfect.  Going to commit/push and do a NuGet update on this now!

**Comment by jchristn** [comment]
Commit is here - thanks again :)  https://github.com/jchristn/WatsonWebserver/commit/5455df812194b0afaf68b419cd1d183fbba64971

**Comment by KKoustas** [comment]
I .m glad that  was helpful.
Great  work you have done :)

**Comment by jchristn** [comment]
Thank you!!  Glad you enjoy it!
