### ISSUE TITLE
Accessing from outside response "Bad Request-Invalid Hostname"

### ISSUE THREAD

**Issue by Jycjmf** [jchristn/WatsonWebserver#60]
HI!
I want to access the WebServer from outside, but it response "Bad Request-Invalid Hostname"; I have read the ReadMe about "Accessing from Outside Localhost", but I cannot understand the actual mean of  " exact DNS hostname ". 
Here is my constructor, I just use localhost as hostname
```
    Server s = new Server("localhost", 2333, false, DefaultRoute);
    s.Start();
```
And here is my POST request, I added the headers named "Host" and the value is "localhost":
![image](https://user-images.githubusercontent.com/30173232/112746799-d8a56c00-8fe3-11eb-8bcf-7b183ea0d034.png)

I have already binding the URL like below:
![image](https://user-images.githubusercontent.com/30173232/112746878-81ec6200-8fe4-11eb-8635-c7984f549919.png)

And this is my public ip address : 39.99.135.10 , I just want to access the webserver from outer ip address, what should I do?
Thanks!

**Comment by jchristn** [comment]
Hi @Jycjmf if you set your listener to localhost it will not accept external connections. Try setting the listener IP to your public IP address. Also you shouldn't have to manually set the HOST header. Postman may automatically set it for you based on the URL. 

Cheers, Joel

**Comment by jchristn** [comment]
Also change your URL reservation/ACL from local host to either + or *

**Comment by jchristn** [comment]
Hi @Jycjmf wasn't sure if you saw my edits above.  I made them after the original response, so the update may not have come across your email.  Cheers, Joel
