### ISSUE TITLE
Adding public property about the server's status

### ISSUE THREAD

**Issue by mor-vino** [jchristn/WatsonWebserver#7]
Hello,
I'm using the WatsonWebServer in my project.
I am holding an instance of the "Server" object and i have noticed i have no indication about the Http listener status, for example, i don't know if the listener encountered an exception and closed (except to the Console printings). 
As a solution, i added the public property as follow:

![image](https://user-images.githubusercontent.com/12879434/29304912-82b83144-819e-11e7-9b90-a4749cd42c5b.png)

Another solution, is replacing the Boolean property with an Enum representing the status (Initializing\Listening\closedDueToException, etc...)

**Comment by jchristn** [comment]
Hi @mor-vino this is an excellent suggestion, I'll add this today and get NuGet updated with it!  Thanks so much!

**Comment by jchristn** [comment]
Committed, pushed, and updated NuGet.  Thanks so much for the contribution @mor-vino  https://github.com/jchristn/WatsonWebserver/commit/dd58f27fba630164b40395d80e56953d9586aa12

**Comment by mor-vino** [comment]
Thanks a lot!
