### ISSUE TITLE
Server never comes back after stop (.NET Core 3.1)

### ISSUE THREAD

**Issue by deathbull** [jchristn/WatsonWebserver#77]
I tested Test.Default project and as i saw in .net 5 there is no problem it can stop and start immediatly, but in .net core 3.1 it just stopping and can not start again it gives error from AcceptConnections function

![image](https://user-images.githubusercontent.com/48456995/139624484-4ea58a4c-8ae3-46c4-8ed4-59054cb8bb81.png)

**Comment by jchristn** [comment]
Interesting.  Thanks for finding this.  Apparently the ```.Stop()``` method has different behaviors across frameworks.  I've fixed it locally by adding ```_HttpListener = new HttpListener()``` to the ```Start``` methods, and will publish this as a new version momentarily.

**Comment by jchristn** [comment]
NuGet: https://www.nuget.org/packages/Watson/4.2.2.2
Commit: https://github.com/jchristn/WatsonWebserver/commit/b323a3087d2c21938ca90311d41842fb8ea67330

I really appreciate it @deathbull - hope you don't mind I added you to the README too!

**Comment by deathbull** [comment]
Thank you so much
