### ISSUE TITLE
Response data is stripped from certain status codes

### ISSUE THREAD

**Issue by mbcrawfo** [jchristn/WatsonWebserver#8]
I've skimmed through the server code and don't see anything that might be causing this, and when debug is enable the console reports that the response data is there, so I'm thoroughly stumped about the problem.

The example below should take a status code in the request body and echo it back to you using that status code for the response.  For some status codes (e.g. 409 conflict) Postman reports that it gets nothing in the response body, and it's missing all of the headers that should normally be there (Access-Control-Allow-Origin, Content-Length, and Content-Type).

    internal class Program
    {
        public static void Main(string[] args)
        {
            var server = new Server("localhost", 8080, false, Handler, true);

            Console.ReadKey();
            server.Dispose();
        }

        private static HttpResponse Handler(HttpRequest request)
        {
            var bodyData = request.Data ?? new byte[0];
            var bodyString = Encoding.UTF8.GetString(bodyData);
            int statusCode;
            if (!int.TryParse(bodyString, out statusCode))
                statusCode = 404;

            return new HttpResponse(request, true, statusCode, null, "text/plain", bodyString, true);
        }
    }

**Comment by jchristn** [comment]
Hi @mbcrawfo  it looks like this is the behavior anytime a status code is used that isn't accounted for in BuildErrorResponse and SendResponse.  I tried with 200, 201, 400, 404, etc, and they returned the correct headers.  Can you confirm that is the case?  If so, I can add 409 an any other status codes you wish to use that I may have missed.  Thanks!

**Comment by jchristn** [comment]
Hi @mbcrawfo I just committed a fix and also updated NuGet (see https://github.com/jchristn/WatsonWebserver/commit/aeb708198b5c4ef92e97d1c184fe41f72a7adc36) - could you re-open if this doesn't work as expected for you?  Thanks!
