### ISSUE TITLE
Windows 10, only 127.0.0.1 works as IP

### ISSUE THREAD

**Issue by AChmieletzki** [jchristn/WatsonWebserver#9]
When running the library on a Windows 10 System, the only IP I can give the HTTP Server is "127.0.0.1", the real IP of the Host as well as "0.0.0.0" get ignored and the Server never starts to listen.
Thus, even if my server is opened on 127.0.0.1, only the host system can actually send a request to the server, but any other client system can't.

Perhaps it's an issue with our PCs in the office (Windows 7 systems work fine btw), but I thought I'd let you know about this.

**Comment by jchristn** [comment]
Hi @AChmieletzki are you running with administrative privileges?  I'm able to start Watson using "*" which accepts connections on any IP.  "+" also worked.  I'll have to add a check for cases where "0.0.0.0" is passed in and use IPAddress.Any instead.  Please let me know if "*" or "+" work for you.  Thanks!

**Comment by jchristn** [comment]
Hi @AChmieletzki I changed it up a bit to accept null and asterisk as input parameters on the constructor so it would be able to accept connections on any IP.  Also updated NuGet to v1.2.9 with this fix.  Please let me know if any further issues!

**Comment by AChmieletzki** [comment]
Sadly the issue still persists on my end. I tried "*", "+", null, "", IPAddress.Any.ToString(), "0.0.0.0" to no avail. Starting the executable (as well as Visual Studio itself) as admin has no effect either.

The strange thing is that I can start stuff like XAMPP or Websocket Servers just fine on any port that isn't occupied.

**Comment by AChmieletzki** [comment]
Looking through your source code, I noticed that you print out "Exiting" in a finally clause when starting up the server. Which is what I get immediately after starting a server, i.e. it starts and exits right away.
Perhaps one of the two empty Catch clauses are the culprit?

**Comment by jchristn** [comment]
Hi @AChmieletzki since I cannot reproduce on my end (I'm also using Windows 10) would you mind changing the catch/finally blocks to the following and let me know what you see on your screen?

```
            catch (HttpListenerException hle)
            {
                Logging.LogException("AcceptConnections", hle);
            }
            catch (OperationCanceledException oce)
            {
                Logging.LogException("AcceptConnections", oce);
            }
            catch (Exception eOuter)
            {
                Logging.LogException("AcceptConnections", eOuter);
                throw;
            }
            finally
            {
                Logging.Log("Exiting");
            }
```

**Comment by AChmieletzki** [comment]
I resolved it. Logging the exceptions showed me an 'Access Denied' exception. Apparently I forgot to request admin rights for that particular PC.
The funny thing is, I can start applications as admin. It asks me for my credentials, I press OK, application starts but it's still in standard user mode and I don't get a popup or anything that tells me that I'm not actually an admin. Thanks W10 :-D

Thank you for your time and support.

**Comment by jchristn** [comment]
Glad you were able to get it working @AChmieletzki !
